/// A DOM attribute that can be set on elements.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Attr {
    Role,
    Accept,
    AcceptCharset,
    AccessKey,
    Action,
    Alt,
    Async,
    AutoComplete,
    AutoFocus,
    AutoPlay,
    Charset,
    Checked,
    Cite,
    Class,
    Color,
    Cols,
    ColSpan,
    Content,
    ContentEditable,
    Controls,
    Coords,
    Data,
    DateTime,
    Default,
    Defer,
    Dir,
    DirName,
    Disabled,
    Download,
    Draggable,
    DropZone,
    EncType,
    For,
    Form,
    FormAction,
    Headers,
    Height,
    Hidden,
    High,
    Href,
    HrefLang,
    HttpEquiv,
    Id,
    IsMap,
    Kind,
    Label,
    Lang,
    List,
    Loop,
    Low,
    Max,
    MaxLength,
    Media,
    Method,
    Min,
    MinLength,
    Multiple,
    Muted,
    Name,
    NoValidate,
    OnAbort,
    OnAfterPrint,
    OnBeforePrint,
    OnBeforeUnload,
    OnBlur,
    OnCanPlay,
    OnCanPlayThrough,
    OnChange,
    OnClick,
    OnContextMenu,
    OnCopy,
    OnCueChange,
    OnCut,
    OnDblClick,
    OnDrag,
    OnDragEnd,
    OnDragEnter,
    OnDragLeave,
    OnDragOver,
    OnDragStart,
    OnDrop,
    OnDurationChange,
    OnEmptied,
    OnEnded,
    OnError,
    OnFocus,
    OnHashChange,
    OnInput,
    OnInvalid,
    OnKeyDown,
    OnKeyPress,
    OnKeyUp,
    OnLoad,
    OnLoadedData,
    OnLoadedMetaData,
    OnLoadStart,
    OnMouseDown,
    OnMouseMove,
    OnMouseOut,
    OnMouseOver,
    OnMouseUp,
    OnMouseWheel,
    OnOffline,
    OnOnline,
    OnPageHide,
    OnPageShow,
    OnPaste,
    OnPause,
    OnPlay,
    OnPlaying,
    OnPopState,
    OnProgress,
    OnRateChange,
    OnRest,
    OnResize,
    OnScroll,
    OnSearch,
    OnSeeked,
    OnSeeking,
    OnSelect,
    OnStalled,
    OnStorage,
    OnSubmit,
    OnSuspend,
    OnTimeUpdate,
    OnToggle,
    OnUnload,
    OnVolumeChange,
    OnWaiting,
    OnWheel,
    Open,
    Optimum,
    Pattern,
    Placeholder,
    Poster,
    Preload,
    ReadOnly,
    Rel,
    Required,
    Reversed,
    Rows,
    RowSpan,
    Sandbox,
    Scope,
    Selected,
    Shape,
    Size,
    Span,
    SpellCheck,
    Src,
    SrcDoc,
    SrcLang,
    SrcSet,
    Start,
    Step,
    Style,
    TabIndex,
    Target,
    Title,
    Translate,
    Type,
    UseMap,
    Value,
    Width,
    Wrap,
    AccentHeight,
    Accumulate,
    Additive,
    AlignmentBaseline,
    AllowReorder,
    Amplitude,
    ArabicForm,
    Ascent,
    AttributeName,
    AttributeType,
    AutoReverse,
    Azimuth,
    BaseFrequency,
    BaselineShift,
    BaseProfile,
    Bbox,
    Begin,
    Bias,
    By,
    CalcMode,
    CapHeight,
    Clip,
    ClipPathUnits,
    ClipPath,
    ClipRule,
    ColorInterpolation,
    ColorInterpolationFilters,
    ColorProfile,
    ColorRendering,
    ContentScriptType,
    ContentStyleType,
    Cursor,
    Cx,
    Cy,
    Decelerate,
    Descent,
    DiffuseConstant,
    Direction,
    Display,
    Divisor,
    DominantBaseline,
    Dur,
    Dx,
    Dy,
    EdgeMode,
    Elevation,
    EnableBackground,
    End,
    Exponent,
    ExternalResourcesRequired,
    FillOpacity,
    FillRule,
    Filter,
    FilterRes,
    FilterUnits,
    FloodColor,
    FloodOpacity,
    FontFamily,
    FontSize,
    FontSizeAdjust,
    FontStretch,
    FontStyle,
    FontVariant,
    FontWeight,
    Format,
    From,
    Fr,
    Fx,
    Fy,
    G1,
    G2,
    GlyphName,
    GlyphOrientationHorizontal,
    GlyphOrientationVertical,
    GlyphRef,
    GradientTransform,
    GradientUnits,
    Hanging,
    HorizAdvX,
    HorizOriginX,
    Ideographic,
    ImageRendering,
    In,
    In2,
    Intercept,
    K,
    K1,
    K2,
    K3,
    K4,
    KernelMatrix,
    KernelUnitLength,
    Kerning,
    KeyPoints,
    KeySplines,
    KeyTimes,
    LengthAdjust,
    LetterSpacing,
    LightingColor,
    LimitingConeAngle,
    Local,
    MarkerEnd,
    MarkerMid,
    MarkerStart,
    MarkerHeight,
    MarkerUnits,
    MarkerWidth,
    Mask,
    MaskContentUnits,
    MaskUnits,
    Mathematical,
    Mode,
    NumOctaves,
    Offset,
    Opacity,
    Operator,
    Order,
    Orient,
    Orientation,
    Origin,
    Overflow,
    OverlinePosition,
    OverlineThickness,
    Panose1,
    PaintOrder,
    PathLength,
    PatternContentUnits,
    PatternTransform,
    PatternUnits,
    Ping,
    PointerEvents,
    Points,
    PointsAtX,
    PointsAtY,
    PointsAtZ,
    PreserveAlpha,
    PreserveAspectRatio,
    PrimitiveUnits,
    R,
    Radius,
    ReferrerPolicy,
    RefX,
    RefY,
    RenderingIntent,
    RepeatCount,
    RepeatDur,
    RequiredExtensions,
    RequiredFeatures,
    Restart,
    Result,
    Rotate,
    Rx,
    Ry,
    Scale,
    Seed,
    ShapeRendering,
    Slope,
    Spacing,
    SpecularConstant,
    SpecularExponent,
    Speed,
    SpreadMethod,
    StartOffset,
    StdDeviation,
    Stemh,
    Stemv,
    StitchTiles,
    StopColor,
    StopOpacity,
    StrikethroughPosition,
    StrikethroughThickness,
    String,
    Stroke,
    StrokeDashArray,
    StrokeDashOffset,
    StrokeLinecap,
    StrokeLineJoin,
    StrokeMiterLimit,
    StrokeOpacity,
    StrokeWidth,
    SurfaceScale,
    SystemLanguage,
    TableValues,
    TargetX,
    TargetY,
    TextAnchor,
    TextDecoration,
    TextRendering,
    TextLength,
    To,
    Transform,
    U1,
    U2,
    UnderlinePosition,
    UnderlineThickness,
    Unicode,
    UnicodeBidi,
    UnicodeRange,
    UnitsPerEm,
    VAlphabetic,
    VHanging,
    VIdeographic,
    VMathematical,
    Values,
    VectorEffect,
    Version,
    VertAdvY,
    VertOriginX,
    VertOriginY,
    ViewTarget,
    Visibility,
    Widths,
    WordSpacing,
    WritingMode,
    X,
    XHeight,
    X1,
    X2,
    XchannelSelector,
    XlinkActuate,
    XlinkArcrole,
    XlinkHref,
    XlinkRole,
    XlinkShow,
    XlinkTitle,
    XlinkType,
    XmlBase,
    XmlLang,
    XmlSpace,
    Y,
    Y1,
    Y2,
    YchannelSelector,
    Z,
    ZoomAndPan,
    Path,
    D,
    Xmlns,
    ViewBox,
    Fill,
    AriaAtomic,
    AriaBusy,
    AriaControls,
    AriaCurrent,
    AriaDescribedBy,
    AriaDetails,
    AriaDisabled,
    AriaDropEffect,
    AriaErrorMessage,
    AriaFlowto,
    AriaGrabbed,
    AriaHasPopup,
    AriaHidden,
    AriaInvalid,
    AriaKeyShortcuts,
    AriaLabel,
    AriaLabelledBy,
    AriaLive,
    AriaOwns,
    AriaRelevant,
    AriaRoleDescription,
    AriaExpanded,
    AriaDialog,
    AriaPressed,
    AriaChecked,
    AriaColSpan,
    AriaRowIndex,
    AriaRowSpan,
    AriaSort,
    AriaReadonly,
    AriaRequired,
    AriaSelected,
    AriaMultiSelectable,
    AriaActiveDescendant,
    AriaOrientation,
    AriaLevel,
    AriaPosinset,
    AriaSetsize,
    AriaValueMax,
    AriaValueMin,
    AriaValueNow,
    AriaValueText,
    AriaMultiLine,
    AriaPlaceholder,
    // Custom(Cow<'static, str>),
}

impl Attr {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Role => "role",
            Self::Accept => "Accept",
            Self::AcceptCharset => "AcceptCharset",
            Self::AccessKey => "AccessKey",
            Self::Action => "Action",
            Self::Alt => "Alt",
            Self::Async => "Async",
            Self::AutoComplete => "AutoComplete",
            Self::AutoFocus => "AutoFocus",
            Self::AutoPlay => "AutoPlay",
            Self::Charset => "Charset",
            Self::Checked => "Checked",
            Self::Cite => "Cite",
            Self::Class => "Class",
            Self::Color => "Color",
            Self::Cols => "Cols",
            Self::ColSpan => "ColSpan",
            Self::Content => "Content",
            Self::ContentEditable => "ContentEditable",
            Self::Controls => "Controls",
            Self::Coords => "Coords",
            Self::Data => "Data",
            Self::DateTime => "DateTime",
            Self::Default => "Default",
            Self::Defer => "Defer",
            Self::Dir => "Dir",
            Self::DirName => "DirName",
            Self::Disabled => "Disabled",
            Self::Download => "Download",
            Self::Draggable => "Draggable",
            Self::DropZone => "DropZone",
            Self::EncType => "EncType",
            Self::For => "For",
            Self::Form => "Form",
            Self::FormAction => "FormAction",
            Self::Headers => "Headers",
            Self::Height => "Height",
            Self::Hidden => "Hidden",
            Self::High => "High",
            Self::Href => "Href",
            Self::HrefLang => "HrefLang",
            Self::HttpEquiv => "HttpEquiv",
            Self::Id => "Id",
            Self::IsMap => "IsMap",
            Self::Kind => "Kind",
            Self::Label => "Label",
            Self::Lang => "Lang",
            Self::List => "List",
            Self::Loop => "Loop",
            Self::Low => "Low",
            Self::Max => "Max",
            Self::MaxLength => "MaxLength",
            Self::Media => "Media",
            Self::Method => "Method",
            Self::Min => "Min",
            Self::MinLength => "MinLength",
            Self::Multiple => "Multiple",
            Self::Muted => "Muted",
            Self::Name => "Name",
            Self::NoValidate => "NoValidate",
            Self::OnAbort => "OnAbort",
            Self::OnAfterPrint => "OnAfterPrint",
            Self::OnBeforePrint => "OnBeforePrint",
            Self::OnBeforeUnload => "OnBeforeUnload",
            Self::OnBlur => "OnBlur",
            Self::OnCanPlay => "OnCanPlay",
            Self::OnCanPlayThrough => "OnCanPlayThrough",
            Self::OnChange => "OnChange",
            Self::OnClick => "OnClick",
            Self::OnContextMenu => "OnContextMenu",
            Self::OnCopy => "OnCopy",
            Self::OnCueChange => "OnCueChange",
            Self::OnCut => "OnCut",
            Self::OnDblClick => "OnDblClick",
            Self::OnDrag => "OnDrag",
            Self::OnDragEnd => "OnDragEnd",
            Self::OnDragEnter => "OnDragEnter",
            Self::OnDragLeave => "OnDragLeave",
            Self::OnDragOver => "OnDragOver",
            Self::OnDragStart => "OnDragStart",
            Self::OnDrop => "OnDrop",
            Self::OnDurationChange => "OnDurationChange",
            Self::OnEmptied => "OnEmptied",
            Self::OnEnded => "OnEnded",
            Self::OnError => "OnError",
            Self::OnFocus => "OnFocus",
            Self::OnHashChange => "OnHashChange",
            Self::OnInput => "OnInput",
            Self::OnInvalid => "OnInvalid",
            Self::OnKeyDown => "OnKeyDown",
            Self::OnKeyPress => "OnKeyPress",
            Self::OnKeyUp => "OnKeyUp",
            Self::OnLoad => "OnLoad",
            Self::OnLoadedData => "OnLoadedData",
            Self::OnLoadedMetaData => "OnLoadedMetaData",
            Self::OnLoadStart => "OnLoadStart",
            Self::OnMouseDown => "OnMouseDown",
            Self::OnMouseMove => "OnMouseMove",
            Self::OnMouseOut => "OnMouseOut",
            Self::OnMouseOver => "OnMouseOver",
            Self::OnMouseUp => "OnMouseUp",
            Self::OnMouseWheel => "OnMouseWheel",
            Self::OnOffline => "OnOffline",
            Self::OnOnline => "OnOnline",
            Self::OnPageHide => "OnPageHide",
            Self::OnPageShow => "OnPageShow",
            Self::OnPaste => "OnPaste",
            Self::OnPause => "OnPause",
            Self::OnPlay => "OnPlay",
            Self::OnPlaying => "OnPlaying",
            Self::OnPopState => "OnPopState",
            Self::OnProgress => "OnProgress",
            Self::OnRateChange => "OnRateChange",
            Self::OnRest => "OnRest",
            Self::OnResize => "OnResize",
            Self::OnScroll => "OnScroll",
            Self::OnSearch => "OnSearch",
            Self::OnSeeked => "OnSeeked",
            Self::OnSeeking => "OnSeeking",
            Self::OnSelect => "OnSelect",
            Self::OnStalled => "OnStalled",
            Self::OnStorage => "OnStorage",
            Self::OnSubmit => "OnSubmit",
            Self::OnSuspend => "OnSuspend",
            Self::OnTimeUpdate => "OnTimeUpdate",
            Self::OnToggle => "OnToggle",
            Self::OnUnload => "OnUnload",
            Self::OnVolumeChange => "OnVolumeChange",
            Self::OnWaiting => "OnWaiting",
            Self::OnWheel => "OnWheel",
            Self::Open => "Open",
            Self::Optimum => "Optimum",
            Self::Pattern => "Pattern",
            Self::Placeholder => "Placeholder",
            Self::Poster => "Poster",
            Self::Preload => "Preload",
            Self::ReadOnly => "ReadOnly",
            Self::Rel => "Rel",
            Self::Required => "Required",
            Self::Reversed => "Reversed",
            Self::Rows => "Rows",
            Self::RowSpan => "RowSpan",
            Self::Sandbox => "Sandbox",
            Self::Scope => "Scope",
            Self::Selected => "Selected",
            Self::Shape => "Shape",
            Self::Size => "Size",
            Self::Span => "Span",
            Self::SpellCheck => "SpellCheck",
            Self::Src => "Src",
            Self::SrcDoc => "SrcDoc",
            Self::SrcLang => "SrcLang",
            Self::SrcSet => "SrcSet",
            Self::Start => "Start",
            Self::Step => "Step",
            Self::Style => "Style",
            Self::TabIndex => "TabIndex",
            Self::Target => "Target",
            Self::Title => "Title",
            Self::Translate => "Translate",
            Self::Type => "Type",
            Self::UseMap => "UseMap",
            Self::Value => "Value",
            Self::Width => "Width",
            Self::Wrap => "Wrap",
            Self::AccentHeight => "AccentHeight",
            Self::Accumulate => "Accumulate",
            Self::Additive => "Additive",
            Self::AlignmentBaseline => "AlignmentBaseline",
            Self::AllowReorder => "AllowReorder",
            Self::Amplitude => "Amplitude",
            Self::ArabicForm => "ArabicForm",
            Self::Ascent => "Ascent",
            Self::AttributeName => "AttributeName",
            Self::AttributeType => "AttributeType",
            Self::AutoReverse => "AutoReverse",
            Self::Azimuth => "Azimuth",
            Self::BaseFrequency => "BaseFrequency",
            Self::BaselineShift => "BaselineShift",
            Self::BaseProfile => "BaseProfile",
            Self::Bbox => "Bbox",
            Self::Begin => "Begin",
            Self::Bias => "Bias",
            Self::By => "By",
            Self::CalcMode => "CalcMode",
            Self::CapHeight => "CapHeight",
            Self::Clip => "Clip",
            Self::ClipPathUnits => "ClipPathUnits",
            Self::ClipPath => "ClipPath",
            Self::ClipRule => "ClipRule",
            Self::ColorInterpolation => "ColorInterpolation",
            Self::ColorInterpolationFilters => "ColorInterpolationFilters",
            Self::ColorProfile => "ColorProfile",
            Self::ColorRendering => "ColorRendering",
            Self::ContentScriptType => "ContentScriptType",
            Self::ContentStyleType => "ContentStyleType",
            Self::Cursor => "Cursor",
            Self::Cx => "Cx",
            Self::Cy => "Cy",
            Self::Decelerate => "Decelerate",
            Self::Descent => "Descent",
            Self::DiffuseConstant => "DiffuseConstant",
            Self::Direction => "Direction",
            Self::Display => "Display",
            Self::Divisor => "Divisor",
            Self::DominantBaseline => "DominantBaseline",
            Self::Dur => "Dur",
            Self::Dx => "Dx",
            Self::Dy => "Dy",
            Self::EdgeMode => "EdgeMode",
            Self::Elevation => "Elevation",
            Self::EnableBackground => "EnableBackground",
            Self::End => "End",
            Self::Exponent => "Exponent",
            Self::ExternalResourcesRequired => "ExternalResourcesRequired",
            Self::FillOpacity => "FillOpacity",
            Self::FillRule => "FillRule",
            Self::Filter => "Filter",
            Self::FilterRes => "FilterRes",
            Self::FilterUnits => "FilterUnits",
            Self::FloodColor => "FloodColor",
            Self::FloodOpacity => "FloodOpacity",
            Self::FontFamily => "FontFamily",
            Self::FontSize => "FontSize",
            Self::FontSizeAdjust => "FontSizeAdjust",
            Self::FontStretch => "FontStretch",
            Self::FontStyle => "FontStyle",
            Self::FontVariant => "FontVariant",
            Self::FontWeight => "FontWeight",
            Self::Format => "Format",
            Self::From => "From",
            Self::Fr => "Fr",
            Self::Fx => "Fx",
            Self::Fy => "Fy",
            Self::G1 => "G1",
            Self::G2 => "G2",
            Self::GlyphName => "GlyphName",
            Self::GlyphOrientationHorizontal => "GlyphOrientationHorizontal",
            Self::GlyphOrientationVertical => "GlyphOrientationVertical",
            Self::GlyphRef => "GlyphRef",
            Self::GradientTransform => "GradientTransform",
            Self::GradientUnits => "GradientUnits",
            Self::Hanging => "Hanging",
            Self::HorizAdvX => "HorizAdvX",
            Self::HorizOriginX => "HorizOriginX",
            Self::Ideographic => "Ideographic",
            Self::ImageRendering => "ImageRendering",
            Self::In => "In",
            Self::In2 => "In2",
            Self::Intercept => "Intercept",
            Self::K => "K",
            Self::K1 => "K1",
            Self::K2 => "K2",
            Self::K3 => "K3",
            Self::K4 => "K4",
            Self::KernelMatrix => "KernelMatrix",
            Self::KernelUnitLength => "KernelUnitLength",
            Self::Kerning => "Kerning",
            Self::KeyPoints => "KeyPoints",
            Self::KeySplines => "KeySplines",
            Self::KeyTimes => "KeyTimes",
            Self::LengthAdjust => "LengthAdjust",
            Self::LetterSpacing => "LetterSpacing",
            Self::LightingColor => "LightingColor",
            Self::LimitingConeAngle => "LimitingConeAngle",
            Self::Local => "Local",
            Self::MarkerEnd => "MarkerEnd",
            Self::MarkerMid => "MarkerMid",
            Self::MarkerStart => "MarkerStart",
            Self::MarkerHeight => "MarkerHeight",
            Self::MarkerUnits => "MarkerUnits",
            Self::MarkerWidth => "MarkerWidth",
            Self::Mask => "Mask",
            Self::MaskContentUnits => "MaskContentUnits",
            Self::MaskUnits => "MaskUnits",
            Self::Mathematical => "Mathematical",
            Self::Mode => "Mode",
            Self::NumOctaves => "NumOctaves",
            Self::Offset => "Offset",
            Self::Opacity => "Opacity",
            Self::Operator => "Operator",
            Self::Order => "Order",
            Self::Orient => "Orient",
            Self::Orientation => "Orientation",
            Self::Origin => "Origin",
            Self::Overflow => "Overflow",
            Self::OverlinePosition => "OverlinePosition",
            Self::OverlineThickness => "OverlineThickness",
            Self::Panose1 => "Panose1",
            Self::PaintOrder => "PaintOrder",
            Self::PathLength => "PathLength",
            Self::PatternContentUnits => "PatternContentUnits",
            Self::PatternTransform => "PatternTransform",
            Self::PatternUnits => "PatternUnits",
            Self::Ping => "Ping",
            Self::PointerEvents => "PointerEvents",
            Self::Points => "Points",
            Self::PointsAtX => "PointsAtX",
            Self::PointsAtY => "PointsAtY",
            Self::PointsAtZ => "PointsAtZ",
            Self::PreserveAlpha => "PreserveAlpha",
            Self::PreserveAspectRatio => "PreserveAspectRatio",
            Self::PrimitiveUnits => "PrimitiveUnits",
            Self::R => "R",
            Self::Radius => "Radius",
            Self::ReferrerPolicy => "ReferrerPolicy",
            Self::RefX => "RefX",
            Self::RefY => "RefY",
            Self::RenderingIntent => "RenderingIntent",
            Self::RepeatCount => "RepeatCount",
            Self::RepeatDur => "RepeatDur",
            Self::RequiredExtensions => "RequiredExtensions",
            Self::RequiredFeatures => "RequiredFeatures",
            Self::Restart => "Restart",
            Self::Result => "Result",
            Self::Rotate => "Rotate",
            Self::Rx => "Rx",
            Self::Ry => "Ry",
            Self::Scale => "Scale",
            Self::Seed => "Seed",
            Self::ShapeRendering => "ShapeRendering",
            Self::Slope => "Slope",
            Self::Spacing => "Spacing",
            Self::SpecularConstant => "SpecularConstant",
            Self::SpecularExponent => "SpecularExponent",
            Self::Speed => "Speed",
            Self::SpreadMethod => "SpreadMethod",
            Self::StartOffset => "StartOffset",
            Self::StdDeviation => "StdDeviation",
            Self::Stemh => "Stemh",
            Self::Stemv => "Stemv",
            Self::StitchTiles => "StitchTiles",
            Self::StopColor => "StopColor",
            Self::StopOpacity => "StopOpacity",
            Self::StrikethroughPosition => "StrikethroughPosition",
            Self::StrikethroughThickness => "StrikethroughThickness",
            Self::String => "String",
            Self::Stroke => "Stroke",
            Self::StrokeDashArray => "StrokeDashArray",
            Self::StrokeDashOffset => "StrokeDashOffset",
            Self::StrokeLinecap => "StrokeLinecap",
            Self::StrokeLineJoin => "StrokeLineJoin",
            Self::StrokeMiterLimit => "StrokeMiterLimit",
            Self::StrokeOpacity => "StrokeOpacity",
            Self::StrokeWidth => "StrokeWidth",
            Self::SurfaceScale => "SurfaceScale",
            Self::SystemLanguage => "SystemLanguage",
            Self::TableValues => "TableValues",
            Self::TargetX => "TargetX",
            Self::TargetY => "TargetY",
            Self::TextAnchor => "TextAnchor",
            Self::TextDecoration => "TextDecoration",
            Self::TextRendering => "TextRendering",
            Self::TextLength => "TextLength",
            Self::To => "To",
            Self::Transform => "Transform",
            Self::U1 => "U1",
            Self::U2 => "U2",
            Self::UnderlinePosition => "UnderlinePosition",
            Self::UnderlineThickness => "UnderlineThickness",
            Self::Unicode => "Unicode",
            Self::UnicodeBidi => "UnicodeBidi",
            Self::UnicodeRange => "UnicodeRange",
            Self::UnitsPerEm => "UnitsPerEm",
            Self::VAlphabetic => "VAlphabetic",
            Self::VHanging => "VHanging",
            Self::VIdeographic => "VIdeographic",
            Self::VMathematical => "VMathematical",
            Self::Values => "Values",
            Self::VectorEffect => "VectorEffect",
            Self::Version => "Version",
            Self::VertAdvY => "VertAdvY",
            Self::VertOriginX => "VertOriginX",
            Self::VertOriginY => "VertOriginY",
            Self::ViewTarget => "ViewTarget",
            Self::Visibility => "Visibility",
            Self::Widths => "Widths",
            Self::WordSpacing => "WordSpacing",
            Self::WritingMode => "WritingMode",
            Self::X => "X",
            Self::XHeight => "XHeight",
            Self::X1 => "X1",
            Self::X2 => "X2",
            Self::XchannelSelector => "XchannelSelector",
            Self::XlinkActuate => "XlinkActuate",
            Self::XlinkArcrole => "XlinkArcrole",
            Self::XlinkHref => "XlinkHref",
            Self::XlinkRole => "XlinkRole",
            Self::XlinkShow => "XlinkShow",
            Self::XlinkTitle => "XlinkTitle",
            Self::XlinkType => "XlinkType",
            Self::XmlBase => "XmlBase",
            Self::XmlLang => "XmlLang",
            Self::XmlSpace => "XmlSpace",
            Self::Y => "Y",
            Self::Y1 => "Y1",
            Self::Y2 => "Y2",
            Self::YchannelSelector => "YchannelSelector",
            Self::Z => "Z",
            Self::ZoomAndPan => "ZoomAndPan",
            Self::Path => "Path",
            Self::D => "D",
            Self::Xmlns => "Xmlns",
            Self::ViewBox => "ViewBox",
            Self::Fill => "Fill",
            Self::AriaAtomic => "AriaAtomic",
            Self::AriaBusy => "AriaBusy",
            Self::AriaControls => "AriaControls",
            Self::AriaCurrent => "AriaCurrent",
            Self::AriaDescribedBy => "AriaDescribedBy",
            Self::AriaDetails => "AriaDetails",
            Self::AriaDisabled => "AriaDisabled",
            Self::AriaDropEffect => "AriaDropEffect",
            Self::AriaErrorMessage => "AriaErrorMessage",
            Self::AriaFlowto => "AriaFlowto",
            Self::AriaGrabbed => "AriaGrabbed",
            Self::AriaHasPopup => "AriaHasPopup",
            Self::AriaHidden => "AriaHidden",
            Self::AriaInvalid => "AriaInvalid",
            Self::AriaKeyShortcuts => "AriaKeyShortcuts",
            Self::AriaLabel => "aria-label",
            Self::AriaLabelledBy => "AriaLabelledBy",
            Self::AriaLive => "AriaLive",
            Self::AriaOwns => "AriaOwns",
            Self::AriaRelevant => "AriaRelevant",
            Self::AriaRoleDescription => "AriaRoleDescription",
            Self::AriaExpanded => "AriaExpanded",
            Self::AriaDialog => "AriaDialog",
            Self::AriaPressed => "AriaPressed",
            Self::AriaChecked => "AriaChecked",
            Self::AriaColSpan => "AriaColSpan",
            Self::AriaRowIndex => "AriaRowIndex",
            Self::AriaRowSpan => "AriaRowSpan",
            Self::AriaSort => "AriaSort",
            Self::AriaReadonly => "AriaReadonly",
            Self::AriaRequired => "AriaRequired",
            Self::AriaSelected => "AriaSelected",
            Self::AriaMultiSelectable => "AriaMultiSelectable",
            Self::AriaActiveDescendant => "AriaActiveDescendant",
            Self::AriaOrientation => "AriaOrientation",
            Self::AriaLevel => "AriaLevel",
            Self::AriaPosinset => "AriaPosinset",
            Self::AriaSetsize => "AriaSetsize",
            Self::AriaValueMax => "AriaValueMax",
            Self::AriaValueMin => "AriaValueMin",
            Self::AriaValueNow => "AriaValueNow",
            Self::AriaValueText => "AriaValueText",
            Self::AriaMultiLine => "AriaMultiLine",
            Self::AriaPlaceholder => "AriaPlaceholder",
            // Self::Custom(value) => value.as_ref(),
        }
    }
}
