#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub enum Event {
    Cached,
    Error,
    Abort,
    Load,
    BeforeUnload,
    Unload,
    Online,
    Offline,
    Focus,
    Blur,
    Open,
    Message,
    Close,
    PageHide,
    PageShow,
    PopState,
    AnimationStart,
    AnimationEnd,
    AnimationIteration,
    TransitionStart,
    TransitionEnd,
    TranstionRun,
    Rest,
    Submit,
    BeforePrint,
    AfterPrint,
    CompositionStart,
    CompositionUpdate,
    CompositionEnd,
    FullScreenChange,
    FullScreenError,
    Resize,
    Scroll,
    Cut,
    Copy,
    Paste,
    KeyDown,
    KeyUp,
    KeyPress,
    AuxClick,
    Click,
    ContextMenu,
    DblClick,
    MouseDown,
    MouseEnter,
    MouseLeave,
    MouseMove,
    MouseOver,
    MouseOut,
    MouseUp,
    PointerLockChange,
    PointerLockError,
    Select,
    Wheel,
    PointerOver,
    PointerEnter,
    PointerDown,
    PointerMove,
    PointerUp,
    PointerCancel,
    PointerOut,
    PointerLeave,
    GotPointerCapture,
    LostPointerCapture,
    TouchStart,
    TouchEnd,
    TouchCancel,
    TouchMove,
    Drag,
    DragEnd,
    DragEnter,
    DragStart,
    DragLeave,
    DragOver,
    Drop,
    AudioProcess,
    CanPlay,
    CanPlayThrough,
    Complete,
    DurationChange,
    Emptied,
    Ended,
    LoadedData,
    LoadedMetaData,
    Pause,
    Play,
    Playing,
    RateChange,
    Seeked,
    Seeking,
    Stalled,
    Suspend,
    TimeUpdate,
    VolumeChange,
    Waiting,
    LoadEnd,
    LoadStart,
    Timeout,
    Change,
    Storage,
    Checking,
    Downloading,
    NoUpdate,
    Obselete,
    UpdateReady,
    Broadcast,
    CheckBoxStateChange,
    HasChange,
    Input,
    RadioStateChange,
    ReadyStateChange,
    ValueChange,
    Invalid,
    Show,
    SVGAbort,
    SVGError,
    SVGLoad,
    SVGResize,
    SVGScroll,
    SVGUnload,
    Blocked,
    Success,
    UpgradeNeeded,
    VersionChange,
    AfterScriptExecute,
    BeforeScriptExecute,
    DOMMenuItemActive,
    DOMMenuItemInactive,
    PopupHidden,
    PopupHiding,
    PopupShowing,
    PopupShown,
    VisibilityChange,
    ChargingChange,
    ChargingTimeChange,
    DischargingTimeChange,
    Connected,
    StateChange,
    DeviceMotion,
    DeviceOrientation,
    OrientationChange,
    SmartCardInsert,
    SmartCardRemove,
    SelectionChange,
    // Custom(Cow<'static, str>),
}

impl Event {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Cached => "cached",
            Self::Error => "error",
            Self::Abort => "abort",
            Self::Load => "load",
            Self::BeforeUnload => "beforeunload",
            Self::Unload => "unload",
            Self::Online => "online",
            Self::Offline => "offline",
            Self::Focus => "focus",
            Self::Blur => "blur",
            Self::Open => "open",
            Self::Message => "message",
            Self::Close => "close",
            Self::PageHide => "pagehide",
            Self::PageShow => "pageshow",
            Self::PopState => "popstate",
            Self::AnimationStart => "animationstart",
            Self::AnimationEnd => "animationend",
            Self::AnimationIteration => "animationiteration",
            Self::TransitionStart => "transitionstart",
            Self::TransitionEnd => "transitionend",
            Self::TranstionRun => "transtionrun",
            Self::Rest => "rest",
            Self::Submit => "submit",
            Self::BeforePrint => "beforeprint",
            Self::AfterPrint => "afterprint",
            Self::CompositionStart => "compositionstart",
            Self::CompositionUpdate => "compositionupdate",
            Self::CompositionEnd => "compositionend",
            Self::FullScreenChange => "fullscreenchange",
            Self::FullScreenError => "fullscreenerror",
            Self::Resize => "resize",
            Self::Scroll => "scroll",
            Self::Cut => "cut",
            Self::Copy => "copy",
            Self::Paste => "paste",
            Self::KeyDown => "keydown",
            Self::KeyUp => "keyup",
            Self::KeyPress => "keypress",
            Self::AuxClick => "auxclick",
            Self::Click => "click",
            Self::ContextMenu => "contextmenu",
            Self::DblClick => "dblclick",
            Self::MouseDown => "mousedown",
            Self::MouseEnter => "mouseenter",
            Self::MouseLeave => "mouseleave",
            Self::MouseMove => "mousemove",
            Self::MouseOver => "mouseover",
            Self::MouseOut => "mouseout",
            Self::MouseUp => "mouseup",
            Self::PointerLockChange => "pointerlockchange",
            Self::PointerLockError => "pointerlockerror",
            Self::Select => "select",
            Self::Wheel => "wheel",
            Self::PointerOver => "pointerover",
            Self::PointerEnter => "pointerenter",
            Self::PointerDown => "pointerdown",
            Self::PointerMove => "pointermove",
            Self::PointerUp => "pointerup",
            Self::PointerCancel => "pointercancel",
            Self::PointerOut => "pointerout",
            Self::PointerLeave => "pointerleave",
            Self::GotPointerCapture => "gotpointercapture",
            Self::LostPointerCapture => "lostpointercapture",
            Self::TouchStart => "touchstart",
            Self::TouchEnd => "touchend",
            Self::TouchCancel => "touchcancel",
            Self::TouchMove => "touchmove",
            Self::Drag => "drag",
            Self::DragEnd => "dragend",
            Self::DragEnter => "dragenter",
            Self::DragStart => "dragstart",
            Self::DragLeave => "dragleave",
            Self::DragOver => "dragover",
            Self::Drop => "drop",
            Self::AudioProcess => "audioprocess",
            Self::CanPlay => "canplay",
            Self::CanPlayThrough => "canplaythrough",
            Self::Complete => "complete",
            Self::DurationChange => "durationchange",
            Self::Emptied => "emptied",
            Self::Ended => "ended",
            Self::LoadedData => "loadeddata",
            Self::LoadedMetaData => "loadedmetadata",
            Self::Pause => "pause",
            Self::Play => "play",
            Self::Playing => "playing",
            Self::RateChange => "ratechange",
            Self::Seeked => "seeked",
            Self::Seeking => "seeking",
            Self::Stalled => "stalled",
            Self::Suspend => "suspend",
            Self::TimeUpdate => "timeupdate",
            Self::VolumeChange => "volumechange",
            Self::Waiting => "waiting",
            Self::LoadEnd => "loadend",
            Self::LoadStart => "loadstart",
            Self::Timeout => "timeout",
            Self::Change => "change",
            Self::Storage => "storage",
            Self::Checking => "checking",
            Self::Downloading => "downloading",
            Self::NoUpdate => "noupdate",
            Self::Obselete => "obselete",
            Self::UpdateReady => "updateready",
            Self::Broadcast => "broadcast",
            Self::CheckBoxStateChange => "checkboxstatechange",
            Self::HasChange => "haschange",
            Self::Input => "input",
            Self::RadioStateChange => "radiostatechange",
            Self::ReadyStateChange => "readystatechange",
            Self::ValueChange => "valuechange",
            Self::Invalid => "invalid",
            Self::Show => "show",
            Self::SVGAbort => "svgabort",
            Self::SVGError => "svgerror",
            Self::SVGLoad => "svgload",
            Self::SVGResize => "svgresize",
            Self::SVGScroll => "svgscroll",
            Self::SVGUnload => "svgunload",
            Self::Blocked => "blocked",
            Self::Success => "success",
            Self::UpgradeNeeded => "upgradeneeded",
            Self::VersionChange => "versionchange",
            Self::AfterScriptExecute => "afterscriptexecute",
            Self::BeforeScriptExecute => "beforescriptexecute",
            Self::DOMMenuItemActive => "dommenuitemactive",
            Self::DOMMenuItemInactive => "dommenuiteminactive",
            Self::PopupHidden => "popuphidden",
            Self::PopupHiding => "popuphiding",
            Self::PopupShowing => "popupshowing",
            Self::PopupShown => "popupshown",
            Self::VisibilityChange => "visibilitychange",
            Self::ChargingChange => "chargingchange",
            Self::ChargingTimeChange => "chargingtimechange",
            Self::DischargingTimeChange => "dischargingtimechange",
            Self::Connected => "connected",
            Self::StateChange => "statechange",
            Self::DeviceMotion => "devicemotion",
            Self::DeviceOrientation => "deviceorientation",
            Self::OrientationChange => "orientationchange",
            Self::SmartCardInsert => "smartcardinsert",
            Self::SmartCardRemove => "smartcardremove",
            Self::SelectionChange => "selectionchange",
            // Self::Custom(cow) => cow.as_ref(),
        }
    }

    pub fn from_str(value: &str) -> Option<Self> {
        let x = match value {
            "cached" => Self::Cached,
            "error" => Self::Error,
            "abort" => Self::Abort,
            "load" => Self::Load,
            "beforeunload" => Self::BeforeUnload,
            "unload" => Self::Unload,
            "online" => Self::Online,
            "offline" => Self::Offline,
            "focus" => Self::Focus,
            "blur" => Self::Blur,
            "open" => Self::Open,
            "message" => Self::Message,
            "close" => Self::Close,
            "pagehide" => Self::PageHide,
            "pageshow" => Self::PageShow,
            "popstate" => Self::PopState,
            "animationstart" => Self::AnimationStart,
            "animationend" => Self::AnimationEnd,
            "animationiteration" => Self::AnimationIteration,
            "transitionstart" => Self::TransitionStart,
            "transitionend" => Self::TransitionEnd,
            "transtionrun" => Self::TranstionRun,
            "rest" => Self::Rest,
            "submit" => Self::Submit,
            "beforeprint" => Self::BeforePrint,
            "afterprint" => Self::AfterPrint,
            "compositionstart" => Self::CompositionStart,
            "compositionupdate" => Self::CompositionUpdate,
            "compositionend" => Self::CompositionEnd,
            "fullscreenchange" => Self::FullScreenChange,
            "fullscreenerror" => Self::FullScreenError,
            "resize" => Self::Resize,
            "scroll" => Self::Scroll,
            "cut" => Self::Cut,
            "copy" => Self::Copy,
            "paste" => Self::Paste,
            "keydown" => Self::KeyDown,
            "keyup" => Self::KeyUp,
            "keypress" => Self::KeyPress,
            "auxclick" => Self::AuxClick,
            "click" => Self::Click,
            "contextmenu" => Self::ContextMenu,
            "dblclick" => Self::DblClick,
            "mousedown" => Self::MouseDown,
            "mouseenter" => Self::MouseEnter,
            "mouseleave" => Self::MouseLeave,
            "mousemove" => Self::MouseMove,
            "mouseover" => Self::MouseOver,
            "mouseout" => Self::MouseOut,
            "mouseup" => Self::MouseUp,
            "pointerlockchange" => Self::PointerLockChange,
            "pointerlockerror" => Self::PointerLockError,
            "select" => Self::Select,
            "wheel" => Self::Wheel,
            "pointerover" => Self::PointerOver,
            "pointerenter" => Self::PointerEnter,
            "pointerdown" => Self::PointerDown,
            "pointermove" => Self::PointerMove,
            "pointerup" => Self::PointerUp,
            "pointercancel" => Self::PointerCancel,
            "pointerout" => Self::PointerOut,
            "pointerleave" => Self::PointerLeave,
            "gotpointercapture" => Self::GotPointerCapture,
            "lostpointercapture" => Self::LostPointerCapture,
            "touchstart" => Self::TouchStart,
            "touchend" => Self::TouchEnd,
            "touchcancel" => Self::TouchCancel,
            "touchmove" => Self::TouchMove,
            "drag" => Self::Drag,
            "dragend" => Self::DragEnd,
            "dragenter" => Self::DragEnter,
            "dragstart" => Self::DragStart,
            "dragleave" => Self::DragLeave,
            "dragover" => Self::DragOver,
            "drop" => Self::Drop,
            "audioprocess" => Self::AudioProcess,
            "canplay" => Self::CanPlay,
            "canplaythrough" => Self::CanPlayThrough,
            "complete" => Self::Complete,
            "durationchange" => Self::DurationChange,
            "emptied" => Self::Emptied,
            "ended" => Self::Ended,
            "loadeddata" => Self::LoadedData,
            "loadedmetadata" => Self::LoadedMetaData,
            "pause" => Self::Pause,
            "play" => Self::Play,
            "playing" => Self::Playing,
            "ratechange" => Self::RateChange,
            "seeked" => Self::Seeked,
            "seeking" => Self::Seeking,
            "stalled" => Self::Stalled,
            "suspend" => Self::Suspend,
            "timeupdate" => Self::TimeUpdate,
            "volumechange" => Self::VolumeChange,
            "waiting" => Self::Waiting,
            "loadend" => Self::LoadEnd,
            "loadstart" => Self::LoadStart,
            "timeout" => Self::Timeout,
            "change" => Self::Change,
            "storage" => Self::Storage,
            "checking" => Self::Checking,
            "downloading" => Self::Downloading,
            "noupdate" => Self::NoUpdate,
            "obselete" => Self::Obselete,
            "updateready" => Self::UpdateReady,
            "broadcast" => Self::Broadcast,
            "checkboxstatechange" => Self::CheckBoxStateChange,
            "haschange" => Self::HasChange,
            "input" => Self::Input,
            "radiostatechange" => Self::RadioStateChange,
            "readystatechange" => Self::ReadyStateChange,
            "valuechange" => Self::ValueChange,
            "invalid" => Self::Invalid,
            "show" => Self::Show,
            "svgabort" => Self::SVGAbort,
            "svgerror" => Self::SVGError,
            "svgload" => Self::SVGLoad,
            "svgresize" => Self::SVGResize,
            "svgscroll" => Self::SVGScroll,
            "svgunload" => Self::SVGUnload,
            "blocked" => Self::Blocked,
            "success" => Self::Success,
            "upgradeneeded" => Self::UpgradeNeeded,
            "versionchange" => Self::VersionChange,
            "afterscriptexecute" => Self::AfterScriptExecute,
            "beforescriptexecute" => Self::BeforeScriptExecute,
            "dommenuitemactive" => Self::DOMMenuItemActive,
            "dommenuiteminactive" => Self::DOMMenuItemInactive,
            "popuphidden" => Self::PopupHidden,
            "popuphiding" => Self::PopupHiding,
            "popupshowing" => Self::PopupShowing,
            "popupshown" => Self::PopupShown,
            "visibilitychange" => Self::VisibilityChange,
            "chargingchange" => Self::ChargingChange,
            "chargingtimechange" => Self::ChargingTimeChange,
            "dischargingtimechange" => Self::DischargingTimeChange,
            "connected" => Self::Connected,
            "statechange" => Self::StateChange,
            "devicemotion" => Self::DeviceMotion,
            "deviceorientation" => Self::DeviceOrientation,
            "orientationchange" => Self::OrientationChange,
            "smartcardinsert" => Self::SmartCardInsert,
            "smartcardremove" => Self::SmartCardRemove,
            "selectionchange" => Self::SelectionChange,
            // other => Self::Custom(Cow::Owned(other.to_string())),
            _other => {
                return None;
            }
        };
        Some(x)
    }
}
