[package]
name = "bench"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

# [profile.release]
# debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
brass = { path = "../brass" }
wasm-bindgen = "0.2.75"
